### ISSUE TITLE
PruneCluster and React.js

### ISSUE THREAD

**Issue by n0ne** [SINTEF-9012/PruneCluster#102]
Hi.
Do you plan React.js version?
Or maybe you know React Component for PruneCluster...
Thank you.

**Comment by yellowiscool** [comment]
Hi,
No, no plan for react, and I don't know a react component for PruneCluster.

**Comment by n0ne** [comment]
Thank you (-:

**Comment by thomasrosen** [comment]
If anybody stumbles upon this issue:
You can use it in react without having a component. See: https://stackoverflow.com/questions/34286899/prunecluster-and-react-js

[This should stay closed.]

**Comment by tbaustin** [comment]
@thomasrosen how does 
```js
var P = require('../Lib/PruneCluster');
this.clusterGroup = new P.PruneClusterForLeaflet();
```
show you how to use it in react haha?
