### ISSUE TITLE
Update bower for lastest changes

### ISSUE THREAD

**Issue by FalloutPL** [SINTEF-9012/PruneCluster#114]
I had to use ``` bower install 'https://github.com/SINTEF-9012/PruneCluster.git#154221464d4bc831a365d4ec45372a8bcdd90f19'``` and manually create .d.ts file because version from bower is old. 

Could you update it?

**Comment by yellowiscool** [comment]
Yes. I merged a branch and pushed the tag 2.0.0-beta.2 on Github, it's not selected by default so you should install it like this : `bower install PruneCluster#2.0.0-beta.2`
