### ISSUE TITLE
UPGRADE new version with new features?

### ISSUE THREAD

**Issue by ivanssa** [SINTEF-9012/PruneCluster#121]
Again I would like to congratulate the work, I'm having good results in my app, but I wonder if there is a forecast for the official launch of the next release, there have been several improvements I believe we can now release a new version, I would like you can also evaluate the inclusion in the new version of these improvements implemented below:

**1- Remove Marker function by item type, list and all.**
https://github.com/SINTEF-9012/PruneCluster/issues/92#issuecomment-149767961

**2- Cluster Pulsar include animation**
https://github.com/SINTEF-9012/PruneCluster/issues/118#issue-141181160

To help I created a fork with changes here ...
https://github.com/ivanssa/PruneCluster

And here an **example **of the new features
**https://jsfiddle.net/Navi84/wmyddzsw/5/**

**Comment by yellowiscool** [comment]
Hei, I wanted to say I didn't forget this issue but I don't have time to work on this right now. I should have some time during the fall :)

**Comment by ivanssa** [comment]
Thank you, I would be very happy to work with this brilliant design.
