### ISSUE TITLE
RemoveMarkers won't work

### ISSUE THREAD

**Issue by wahisoufiane** [SINTEF-9012/PruneCluster#128]
Hi,

When I call event function to remove a specific marker, with `prunecluster.RemoveMarkers(marker)` it doesn't remove the marker, and I have to call `prunecluster.RedrawIcons()` then it works!

How could it work without explicitly call the redraw function?

**Comment by yellowiscool** [comment]
Hi,

`RemoveMarkers` requires an array of marker, so maybe you need to call `prunecluster.RemoveMarkers([marker])`.

Also, you must call exclicitely `pruneCluster.ProcessView();` I think.

**Comment by wahisoufiane** [comment]
I did send array of marker like you said.

I tried to call `prunecluster.FitBounds()` function instead of `prunecluster.RedrawIcons()` and it works well, also it prevent a bug of unbind label on removing marker, that redrawIcons didn't unbind.
