### ISSUE TITLE
Cluster by category

### ISSUE THREAD

**Issue by zzzFelix** [SINTEF-9012/PruneCluster#136]
Is it possible to group clusters by category so that all markers in a cluster are of the same category? The color coding indicating which categories are represented in a cluster is neat but does not serve my purpose.

**Comment by yellowiscool** [comment]
Yes, you can use a separate PruneCluster layer for each category. You probably need to personalize the cluster icons to distinguish the categories too.

**Comment by zzzFelix** [comment]
I feel foolish that I didn't think of that. I already was fumbling with the source code. Thank you!

**Comment by yellowiscool** [comment]
Ahah, no problem. It could be a nice feature to have by the way :-)
