### ISSUE TITLE
Multiple tooltips created on zoom

### ISSUE THREAD

**Issue by fjeddy** [SINTEF-9012/PruneCluster#148]
HELLo,

Seems like PruneCluster is adding a new tooltip on top of the old one everytime you zoom in or out. Hence, zooming back and forth 10 times will cause the tooltip to be created 10 times on top of each other.

**Comment by fjeddy** [comment]
This library is broken in so many ways, it has more bugs then functions.

**Comment by simison** [comment]
Hey! Be a little bit more constructive and friendlier, please. People are putting their free time working on this. It's a group effort and you as a user are as much responsible for making/helping to make this library work as anyone already working on it. Just killing everyone's motivation and spirit totally doesn't serve anyone.

Which version of Leaflet are you using? Newer versions might have some issues with PruneCluster. If you look into previous issues, you'll notice that newer versions of Leaflet have changed oh things work and thus this library (which was built during Leaflet 0.7) might have some issues especially with popups/tooltips. There are also some tips and ideas how to get them work.

Pull requests are always welcome, you can make it work for yourself and thus be more productive and useful. :-)

If you can provide exact steps or code to replicate those bugs you're encountering, it would help so much!

**Comment by simison** [comment]
And while at it, you should check also https://github.com/mapbox/supercluster — an excellent library which might be more up to date.

**Comment by fjeddy** [comment]
@simison I came from Supercluster.

Regarding the rest of your comments, then i just hear excuses as to why this isn't working. Asking me to fix what never worked in the first place is not going to happen, would be easier to simply start over.

**Comment by simison** [comment]
@fjeddy I wish you luck in the world of using open source libararies with that attitude! <3

**Comment by simison** [comment]
(@yellowiscool; I recon this can be closed)

**Comment by yellowiscool** [comment]
Ok, this is obviously not a constructive discussion.

**Comment by simison** [comment]
@fjeddy I highly recommend you to read this: https://www.ubuntu.com/about/about-ubuntu/conduct and consider next time your style of communicating.

**Comment by fjeddy** [comment]
@simison I highly recommend you to read this: https://opensource.com/business/13/5/open-source-your-code and consider next time you plan to open source something.

**Comment by yellowiscool** [comment]
@fjeddy Your behaviour is not ok. Please move on.

**Comment by fjeddy** [comment]
@yellowiscool Then stop replying and move on.

**Comment by simison** [comment]
@yellowiscool https://help.github.com/articles/locking-conversations/

**Comment by yellowiscool** [comment]
@simison Thanks for your time 😃 

I blocked and reported this weird user. We only got very positive feedback so far, so it had to happen. I will upload a code-of-conduct because being nice is not obvious for everyone.
