### ISSUE TITLE
Typo in JS of realworld.50000 example.

### ISSUE THREAD

**Issue by BobbyBabes** [SINTEF-9012/PruneCluster#167]
I just bumped into Leaflet and its plugins.

This line : [https://github.com/SINTEF-9012/PruneCluster/blob/master/examples/realworld.50000.html#L40](https://github.com/SINTEF-9012/PruneCluster/blob/master/examples/realworld.50000.html#L40)
There is a typo in it. `addressPoints[i][2]` should be `addressPoints2[i][2]`.

**EDIT1:** Also in this example : [https://github.com/SINTEF-9012/PruneCluster/blob/master/examples/realworld.50000-categories.html#L154](https://github.com/SINTEF-9012/PruneCluster/blob/master/examples/realworld.50000-categories.html#L154)

**Comment by yellowiscool** [comment]
Thanks for the report ! 🍾
