### ISSUE TITLE
Method leafletView.PrepareLeafletMarker in examples doesn't seem to be executed.

### ISSUE THREAD

**Issue by BobbyBabes** [SINTEF-9012/PruneCluster#168]
What is the purpose of rewriting PrepareLeafletMarker in this example: `/examples/realworld.50000-categories.html` ?
[https://github.com/SINTEF-9012/PruneCluster/blob/master/examples/realworld.50000-categories.html#L158-L164](https://github.com/SINTEF-9012/PruneCluster/blob/master/examples/realworld.50000-categories.html#L158-L164)
```JavaScript
leafletView.PrepareLeafletMarker = function (marker, data, category) {
    if (marker.getPopup()) {
        marker.setPopupContent(data.title + " - " + category);
    } else {
        marker.bindPopup(data.title + " - " + category);
    }
};
```

when I add `console.log` to log the category, nothing is logged.
```JavaScript
leafletView.PrepareLeafletMarker = function (marker, data, category) {
    console.log(category);
    if (marker.getPopup()) {
        marker.setPopupContent(data.title + " - " + category);
    } else {
        marker.bindPopup(data.title + " - " + category);
    }
};
```
The same thing happens in the example without categories: `/examples/realworld.50000.html`.

**Comment by yellowiscool** [comment]
I think it's executed. Have you tried to zoom ? It's only executed when markers outside clusters are displayed.

**Comment by BobbyBabes** [comment]
You are right.
With this particular example, I never drilled down to the unclustered stage (individual markers) because I expected that adding the category would only matter when clustered. Looks like I got some more digging to do.
Thanks!
