### ISSUE TITLE
Touch not working with latest Samsung browser

### ISSUE THREAD

**Issue by mstekker** [SINTEF-9012/PruneCluster#207]
Hi,

Using iOS I am able to touch a cluster to zoom in till single marker level, and to touch a single marker to see the pop up.

On a Samsung S21, Samsung browser, both are not working. Any suggestions what could be wrong?

Best regards,

Mart

**Comment by fungiboletus** [comment]
Hi,

This library simply uses [the Leaflet `click` event on markers](https://leafletjs.com/reference.html#marker-click). If you create a marker in leaflet, do you get the click events using Samsung browser?

**Comment by mstekker** [comment]
Hi,

Thanks, I digged into the problem. Seems that some kind of VPN solutions messes up the javascript code. So prunecluster is working well :)

**Comment by fungiboletus** [comment]
Thanks for letting me know 🙂
