### ISSUE TITLE
Documentation unclear on several points

### ISSUE THREAD

**Issue by B45man** [SINTEF-9012/PruneCluster#30]
Hi all,
This is an interesting project, and looks to more versatile than the more popular markercluster plugin! However, there's a thing I can't quite figure out reading the project description and code. I'm trying to edit the 10000 random categories example:

http://sintef-9012.github.io/PruneCluster/examples/random.10000-categories-2.html

I want the cluster icon to be changed based on data stored in the markers. In the code of the above page, I add the following code to the for loop that creates the markers:

marker.data.quantity= Math.floor(Math.random() * 20) + -10;

This adds a data attribute that holds a random value of -10 to 10 in it. I want to edit the cluster icon itself to show a total of all marker's quantity attribute. For example, if there are 10 markers in a cluster, with 8 having a quantity of 10, and 2 having a quantity of -10, the cluster containing these markers should have "60" written on it. 

The first problem I get is this: in order to get the value out of the markers again, I have to loop through all the markers in the cluster. I could do this by adding  this code to the BuildLeafletClusterIcon function:

var markers = cluster.getClusterMarkers();

However, in order to use this function, I have to do this:

"(you must enable the option using PruneCluster.Cluster.ENABLE_MARKERS_LIST = true)" 

But I can't figure out where to put this line of code. I have pasted this line to several places in my code, but I keep getting the error that cluster.getClusterMarkers() is not a function.

Then the second problem: if I got the above code working, and the had a variable that contained the sum of the marker quantity data (60 in my example), I don't see how to pass this variable to the draw function from the BuildLeafletClusterIcon function. 

Can someone please explain how to do this?

**Comment by yellowiscool** [comment]
I close this issue, but feel free to reopen it if you still need help.
