### ISSUE TITLE
Accessing markers inside a cluster

### ISSUE THREAD

**Issue by RobbieTheWagner** [SINTEF-9012/PruneCluster#36]
I'm trying to hover a document, and pulse the cluster that the points from that document are in, I know I can find the markers inside a cluster if I have the cluster already, but for each document I am just saving the markers. How can I look up the cluster if I know the markers?

**Comment by anshudaur** [comment]
HI, Is there any solution without PruneCluster ? I need help as for two location which are separated by 1 mile or less , the cluster for them doesn't zoom in.
Thank In Advance

**Comment by yellowiscool** [comment]
Hei @anshudaur. I don't really understand, could you open another issue with more details, such as a screenshot for example ?
