### ISSUE TITLE
PruneCluster with ContextMenu

### ISSUE THREAD

**Issue by brainheshmat** [SINTEF-9012/PruneCluster#38]
Hi there,

I have been able to use MarkerCluster with contextmenu but my similar implementation with PruneCluster is not working.  Here is my code:

```javascript
var marker = new PruneCluster.Marker(coordinates[1],coordinates[0], {
				icon: L.divIcon({ 
				    	className: 'class-name',
						iconSize: new L.Point(width, height), 
						html: svg
						}),
						contextmenu: true,							    
						contextmenuItems: [
							{
								text: 'Show Information',
								index: 0,
								value:"name",
								callback:function(key,options){
									}},
							{
								separator: true,
								index: 1 }
						]
			});
			pruneCluster.RegisterMarker(marker);
```
Any help would put me one step closer to demoing this to my manager.

Thanks,
Brian

**Comment by DanielRuf** [comment]
@yellowiscool is this now implemented and how can we use this?

**Comment by DanielRuf** [comment]
@brainheshmat how did you solve it (with a current version of Leaflet, PruneCluster and contextmenu)?
