### ISSUE TITLE
Slow drag

### ISSUE THREAD

**Issue by steros76** [SINTEF-9012/PruneCluster#42]
Using PruneCluster, if I create a single marker (not part of a cluster), dragging it is very slow. If I remove PruneCluster include or if I use MarkerCluster, the drag speed is ok.

I create a test page (it's your example with a draggable marker added) at http://jsfiddle.net/neup69fo/

**Comment by simison** [comment]
Works well here too, thanks.

**Comment by yellowiscool** [comment]
I fixed the bug in the version 1.1.0. But you don't need to update your code, the "no-anim" class is just useless now.
