### ISSUE TITLE
remove prune cluster instance

### ISSUE THREAD

**Issue by badgeek** [SINTEF-9012/PruneCluster#43]
when i have

    pruneCluster = new PruneClusterForLeaflet()

is it possible to destroy it? like pruneCluster.remove() ?

**Comment by yellowiscool** [comment]
PruneClusterForLeaflet implements the [Leaflet ILayer](http://leafletjs.com/reference.html#ilayer) interface.

You can remove it like any other layer :
```javascript
map.removeLayer(pruneCluster);
```

**Comment by badgeek** [comment]
doest it will remove pruneCluster from the memory? offcourse after we clear all the marker and listener

thanks

**Comment by yellowiscool** [comment]
The layers and event listeners are removed from leaflet. 
I haven't check but the garbage collector should work. Don't forget to remove the references of the pruneCluster object (with ```delete pruneCluster;``` for example).

**Comment by yellowiscool** [comment]
I'm closing old issues. Feel free to reopen it if you still need help.
