### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by rolanddu** [SINTEF-9012/PruneCluster#45]
I am just starting to explore using PruneCluster.  When I attempt to download and run a PruneCluster example locally I receive the following console error:

ReferenceError: L is not defined on line 352 of PruneCluster.js

Also: the same reference error on line 19 of random.100.html

I am running random.100.html locally.  Any guidance would be appreciated.

Thanks,
Roland

**Comment by yellowiscool** [comment]
Hi,

L is Leaflet's namespace. I think the library is not loaded from the CDN server because you are using it locally (the URL starts with file://).

You can download Leaflet separately and change the script and CSS locations in the examples, or load the examples using a HTTP server.

**Comment by rolanddu** [comment]
That was it.  Thanks Yellowiscool.  I ran a Python server (python -m SimpleHTTPServer) on the folder and then accessed the example using http://localhost:8000/examples/random.100.html

Thanks Again,
Roland
