### ISSUE TITLE
Minimizing Clicks and getting bounds for filtered markers

### ISSUE THREAD

**Issue by smitchell** [SINTEF-9012/PruneCluster#48]
Please see: http://www.exploringspatial.com/#demo/6

This is roughly how I'm doing interactive filtering. Is it necessary to remove the markers first?
```javascript
var markers = layer.GetMarkers();
layer.RemoveMarkers();
var marker;
for (var i =0; i<markers.length,i++){
    marker = marker[i];
    marker.filter = this.search.filterMarker(marker.data);
    layer.RegisterMarker(marker);
}
layer.ProcessView();
layer.FitBounds();
```
The problem with my approach is that FitBounds() includes filtered markers. I really want to zoom in on the markers that are visible. What is the best way to do this? If I eliminate the RemoveMarkers() and RegisterMarker(), and just toggle the filter attribute and run ProcessView(), nothing changes.

The  other issue, especially when filtering, is that some clusters must be clicked three or four clicks that only change the zoom before the cluster expands, even though no other markers or clusters are visible on the map. My expectation was that when I click the cluster it should expand. I should have to click it 4 times.

Thanks!

**Comment by yellowiscool** [comment]
Hi,

No, it's not necessary to remove the markers. I think the problem is that you use ```marker.filter``` instead of ```marker.filtered```.

FitBounds() includes filtered markers and I don't see think it should. It will change in the future but you can try this:

```javascript
var fitBounds = function(layer) {
   var allMarkers = layer.Cluster.GetMarkers();
   var markers = [];
   for (var i = 0, l = allMarkers.length; i < l; ++i) {
      if (!allMarkers[i].filtered) {
         markers.push(allMarkers[i]);
      }
   }
   var bounds = layer.Cluster.ComputeBounds(markers);

   if (bounds) {
     layer._map.fitBounds(new L.LatLngBounds(
       new L.LatLng(bounds.minLat, bounds.maxLng),
       new L.LatLng(bounds.maxLat, bounds.minLng)));
   }
}
```

Regarding the clicks problem, I have tried your nice demo, but I don't have this problem. Once I dragged the map by 1 pixel instead of clicking. It may be related.

**Comment by smitchell** [comment]
Thanks, Antoine. You were absolutely right about removing the markers. I think I must have added that when I was debugging my filter logic. I took a slightly different approach to patching fitBounds(). I think this may reduce the number of clicks required to expanded a cluster, especially on country searching, now that my map zooms in.

Here is the final code that I went with. It is in the doFilter() method near the bottom of the page:
https://github.com/smitchell/exploringspatial/blob/master/js/views/acled/ArmedConflictLocationsView.js

**Comment by smitchell** [comment]
I think my demo would be improved if my individual markers showed the number of fatalities, and the marker clusters show the sum of the underlying fatalities. I think I saw you had examples of something similar. I'll check it out once I finishing reworking the UI for filtering markers. It has some usability issues.

**Comment by yellowiscool** [comment]
I'm closing old issues. Feel free to reopen it if necessary.
