### ISSUE TITLE
Dealing with multiple categories

### ISSUE THREAD

**Issue by skobeo** [SINTEF-9012/PruneCluster#55]
Hi,
is there a way to dea with multiple categories like 1,2 instead of just 1 ? So we could have only one marker in the main view and at least one marker in each category layer ?
thanks and congratulations for your work

**Comment by yellowiscool** [comment]
Hello,
No a marker can have only one category. You can use the filtering system instead, or have some kind of virtual categories (for example 1,2 is the category 3).

**Comment by skobeo** [comment]
thanks for answer. I'll ty to deal with ajax dynamic layers because i have to deal with more than 20k markers, 12 categories and all markers are at least in 2 or 2 cats.
