### ISSUE TITLE
Show all markers without clusters with custom zoom

### ISSUE THREAD

**Issue by Vitalik74** [SINTEF-9012/PruneCluster#57]
In may application I want show all markers if zoom > 15. First, I think change `leafletView.Cluster.Size = 1;`. But I have many `Lapping Markers` and cluster show in this marker and marker show on map stand not well. Second, I think set `this._map.fire('overlappingmarkers', ...)` to show `Lapping Markers`.  But it is not work. 

Finally, I want get like that http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld-maxzoom.388.html . They use option `disableClusteringAtZoom`.

**Comment by yellowiscool** [comment]
The library doesn't support this feature (yet). It's an enhancement already on the TODO list but I don't have time to work on it these months.
You can check the issue #52. I suggest to remove the PruneCluster layer when the zoom is greater than 15, and use directly Leaflet markers instead.
