### ISSUE TITLE
Group by categories

### ISSUE THREAD

**Issue by Sinusite** [SINTEF-9012/PruneCluster#62]
Hi
Is there a way to goup markers only by categories (i.e. each cluster contains only a certain category) ?
Nice work. Thanks.

**Comment by yellowiscool** [comment]
Hello,

Thank you :-)
You can try to create one prunecluster layer for each category.

**Comment by Sinusite** [comment]
wow quick answer ! 
Okay... I will try that asap & back.
Thank U :)
