### ISSUE TITLE
Marker clusters not redrawn when navigating back to the map.

### ISSUE THREAD

**Issue by kripton69** [SINTEF-9012/PruneCluster#72]
In an angular app with single route, marker clusters are not redrawn when navigating to the map route the second time round.

**Comment by yellowiscool** [comment]
You can try to call ProcessView manually. You can also try to use «leafletMap.invalidateSize({ animate: false, pan: false });».

**Comment by kripton69** [comment]
Unfortunately it does not solve my problem. If I have two markers and move the map or zoom, and change the template and go back to map he redraw the markers, because he cluster the markers. But if I only have a single marker he not redraws the marker.

**Comment by yellowiscool** [comment]
Are you sure it's a problem with PruneCluster and not Leaflet in Angular? If you have time, can you make a jsfiddle (or equivalent) to reproduce the problem, so I can better understand it.

I developed PruneCluster for an Angular (1) application and I don't remember having this problem.

**Comment by kripton69** [comment]
Yes the problem are in Leaflet to Angular. My web app is to complex to reproduce the problem in jsfiddle.
Thanks for helping.

**Comment by yellowiscool** [comment]
I don't think it's a beautiful solution, but it worked in my case: I moved the leaflet map outside angular and I manipulated it through an angular service. The map was a <div> directly added to the document.body so it had nothing to do with the scopes, views and routes.
