### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by pedroetb** [SINTEF-9012/PruneCluster#73]
At [Setting up a custom cluster icon](https://github.com/SINTEF-9012/PruneCluster#setting-up-a-custom-cluster-icon), the method *cluster.getClusterMarkers()* doesn't exist.

Searching in issues, I have seen [this](https://github.com/SINTEF-9012/PruneCluster/blob/master/examples/random.10000-getclustermarkers.html#L32), where I saw the correct method's name is **GetClusterMarkers** (capitalized).

**Comment by yellowiscool** [comment]
Thank you, I corrected the readme.

**Comment by valerio-bozzolan** [comment]
Please think about replacing it with ```getClusterMarkers``` that is a better "camel" notation. I think that you can leave both deprecating the first with a ```console.log``` warning.

**Comment by yellowiscool** [comment]
I wrote the library using [.Net Capitalization Conventions](https://msdn.microsoft.com/en-us/library/ms229043%28v=vs.110%29.aspx).
However Leaflet use camel case, so I will probably use camel case next time.

**Comment by valerio-bozzolan** [comment]
OK thanks!
(".Net".. :anguished:)
(".Net conventions".. :fearful:)
