### ISSUE TITLE
zoomToShowLayer function as in markercluster

### ISSUE THREAD

**Issue by bekakst** [SINTEF-9012/PruneCluster#74]
have you got such function?

**Comment by bekakst** [comment]
How can i get markers which is in area with my marker? Or how can i get markers that in same cluster as my marker which is needed?

**Comment by yellowiscool** [comment]
Hi,

zoomToShowLayer is not supported. About the second question, you can use FindMarkersInArea. You will find more information in the readme document.
```var markersArea = pruneCluster.Cluster.FindMarkersInArea(cluster.bounds);```
