### ISSUE TITLE
How can i get leafletMarker from PruneCluster.Marker class object?

### ISSUE THREAD

**Issue by bekakst** [SINTEF-9012/PruneCluster#75]
var marker = new PruneCluster.Marker(latitude, longitude);
var leafletMarker = marker.getLeafletMarker(); - can you do such function?

**Comment by yellowiscool** [comment]
Hi,

No you can't because a PruneCluster.Marker doesn't necessarily contain a LeafletMarker. The LeafletMarkers are created on the fly when needed, and are recycled.
