### ISSUE TITLE
Markers Missing - 83K live system redesign

### ISSUE THREAD

**Issue by itbeyond** [SINTEF-9012/PruneCluster#78]
Excellent plugin however in my testing of different browsers I get different results. I have a system with 83K data items see http://www.exploroz.com/places/prunetest.aspx. This test will load 8 data layers and store them in local storage which contains the 83K items (give it 15 secs to load).

If you open this sample in IE11 it seems to work well (almost perfectly in fact IE is the best browser). I tested with Firefox V39.0 and Chrome 44.0.2403.89 and these two show some similar related problems however Chrome is the worst by far. If you use one of these and zoom into the clusters on the right )the one with 4 specifically) as you get closer the number will drop to 3,2 and none - there are three markers that should be displayed on Lord Howe Is. but in these browsers there will be one or none. You will also note that the mouse click action on the cluster 4 will not work (also most of the green cluster clicks will not work but the 99 at the top seems to work). 

Another specific example is zoom into Perth on the LHS of the Australia IE will show a marker for Perth the other two browsers will not!

it is most strange but in every test the specific things that do not work seem similar between the browsers though Chrome will if you zoom in and out a few times show weird counts in the clusters and on some zoom levels will show no clusters at all.

Any clues or ideas?

**Comment by itbeyond** [comment]
These three samples were made with the map scaled to the exact same spot using fixed width and height for IE, Chrome & FF rendering the exact same test data. You will see the minor difference in FF and the major difference in Chrome, IE seems to be correct.

![ie](https://cloud.githubusercontent.com/assets/1870615/8871455/016cf8a8-3228-11e5-9c6d-c986c0a41a7a.JPG)
![chrome](https://cloud.githubusercontent.com/assets/1870615/8871472/1d791126-3228-11e5-839a-e1b61857cdfe.JPG)
![ff](https://cloud.githubusercontent.com/assets/1870615/8871485/32ab93ca-3228-11e5-827b-fa4c093d299e.JPG)

**Comment by yellowiscool** [comment]
Hi,

Thank you for the report. I can reproduce the problem the report and I have exactly the same result on my browsers.

I don't know what is the problem yet. However I know you have few markers with NaN as latitude/longitudes.

I removed the NaN values with the following code, it's quite slow to execute (maybe NaN problems again), but the results are different.

```javascript
Places_Layer.Cluster._markers.forEach(function(marker) {
    if (isNaN(marker.position.lat) || isNaN(marker.position.lng)) {
        marker.position = {
            lat: -28.80+Math.random()*0.001,
            lng: 114.80+Math.random()*0.001
        };
    }
});

Places_Layer.ProcessView()
```
### Results on Chrome:

#### Before:
![2015-07-24 13_19_00-test](https://cloud.githubusercontent.com/assets/45740/8873448/00472cc6-3207-11e5-9a75-de6b4b47e7a1.png)

#### After:
![2015-07-24 13_21_56-test](https://cloud.githubusercontent.com/assets/45740/8873447/002189f8-3207-11e5-9078-ba150d01d448.png)

Can you check if it fix the problem? I might have to check NaN values in the library.

**Comment by itbeyond** [comment]
Thanks a lot - that actually seemed to fix it. How many darn hours I spent looking for this and I had a extra line terminator at the end of each of the text files. Once I removed these and plugged the new data in it works across the browsers.

Problem resolved - thank you for the pointer and the excellent PlugIn.
