### ISSUE TITLE
Integrate PruneCluster with angular-leaflet-directive? 

### ISSUE THREAD

**Issue by ivanssa** [SINTEF-9012/PruneCluster#89]
Hello guys I'm with the same performance problem when using leaflet for various markers enjoyed the PruneCluster solution is really amazing, but I'm having trouble integrating the script to work with angular in ionic I wonder if someone could help integrate PruneCluster with angular-leaflet-directive? the ionic? It would be really cool if I had a compatible version ...

**Comment by yellowiscool** [comment]
I personally don't plan to support the angular-leaflet-directive, but it might be an interesting side project.

**Comment by simison** [comment]
https://github.com/tombatossals/angular-leaflet-directive/issues/635

**Comment by ivanssa** [comment]
Thank you very much for your help yellowiscool  and simison, it worked.

**Comment by ivanssa** [comment]
Thank you very much for your help yellowiscool and simison, it worked.
