### ISSUE TITLE
Remove specific marker for marker.data.ID and popup in a cluster to display the information?

### ISSUE THREAD

**Issue by ivanssa** [SINTEF-9012/PruneCluster#92]
Hello, I wonder how to remove a specific marker for marker.data.ID also wanted to know if it is possible to open a popup in a cluster to display the information of all markers of the grouping in Statistics style will be very Granto who can help .

**Comment by yellowiscool** [comment]
Hi,
The markers are internally stored in an array, for performances reasons. You can remove a list of markers using `RemoveMarkers`.

An example O(n) algorithm is like this (pseudo code):
```javascript
var markersBeingRemoved = [];
view.GetMarkers().forEach((marker) => {
    if (marker.id === 'an id') markersBeingRemoved.push(marker);
});
view.RemoveMarkers(markersBeingRemoved);
```
You can use a hashmap with the IDs as keys. It may help the performances, but it's up to you for managing it.

When you click on a marker, the only current behaviour is zooming or showing the content if the maximum zoom level is reached. How do you want to open the popup?

The simplest way to open popups is using Leaflet's API directly. See [Map#openPopp](http://leafletjs.com/reference.html#map-openpopup).

**Comment by ivanssa** [comment]
Hello thank you for the answer yellowiscool, really worked the solution to remove points for now, but I will still try to create a custom hash control or a new field with the client code to remove asynchronously and not having to run the vector whenever need to remove only one point, I am currently working with firebase data and he calls the 'child_removed' each time a point is removed so it performs several loops to create the list of removal and this can have loss of performance for many points in the future.

I could not run a popup with the click in the cluster, I would like to get the data for each marker within the cluster in a click in real time and show a statistically with a sum of the data and leave the zoom only by mousewheel something like this http://plnkr.co/edit/pq0203gY6XEB77sAnC1s?p=preview but could not use the markerClusterGroup to return the data of the markers within the cluster with markers.on function ('clusterclick', function (a) {I get undefined for markers [] created by PruneCluster.

**Comment by ivanssa** [comment]
Hello I adapted the code and managed to remove access to vector elements and greatly improved performance, but still can not get the popup in prunecluster cluster with data from real-time marker anyone could help me do like this link http: //plnkr.co/edit/pq0203gY6XEB77sAnC1s?p=preview using prunecluster?

**Comment by yellowiscool** [comment]
It is not supported by the API, but it's still possible to do by overloading a method. Basically, you can start with this code:

```javascript
// overloading BuildLeafletCluster
leafletView.BuildLeafletCluster = function(cluster, position) {
    // Call the existing function first
    var marker = PruneClusterForLeaflet.prototype.BuildLeafletCluster.call(this, cluster, position);

    // Remove all the default event listeners
    marker.off('click');

    // Define a new click event listener computing and displaying the popup
    marker.on('click', function() {
        // Get the markers in the cluster O(n)
        var markersInTheCluster = leafletView.Cluster.FindMarkersInArea(cluster.bounds);

        markersInTheCluster.forEach(function(m) {
            // compute stats
        });

        var popup = L.popup()
            .setLatLng(marker.getLatLng())
            .setContent('<p>'+markersInTheCluster.length+'</p>')
            .openOn(map);
    });

    return marker;
};
```

I should mention than the clustering has no semantic. It's a random grid clustering, for performances reasons. It's probably good enough though.

**Comment by ivanssa** [comment]
Hello yellowiscool would like to thank you very much for your help, I am very happy that everything went well and is working, I had to make only one change in the code to run with ionic with this code snippet:

leafletData.getMap (). Then (function (map) {
         var popup = L.popup ()
.setLatLng (marker.getLatLng ())
.setContent (div)
.openOn (map);
});

Thank you very much the same, see below as was the result:

![charts_ionic](https://cloud.githubusercontent.com/assets/3166174/10536440/6a10767a-73c1-11e5-8da9-280efd099cdd.jpg)

**Comment by yellowiscool** [comment]
You are welcome :-) 

Your application looks good.

**Comment by ivanssa** [comment]
Olá  yellowiscool eu estou tendo alguns avanços no código, tenho apenas uma dúvida estou enviando um código base do PruneCluster funcionando com Angular, eu precisei utilizar uma lista de objetos ao invés de array para poder acessar o item através do código uid, a solução que me passou de remover os pontos através do markersBeingRemoved() funcionou, porém estou trabalhando com firebase e não posso criar uma lista, somente remover um ponto de cada vez e com a esta solução preciso fazer vários forEach e criar vários arrays markersBeingRemoved só pra remover um item o que ficou lento para trabalhar, assim eu consegui estudei e axei uma maneira de remover um item da lista de objetos através do  "delete markers['uidb']" mas o mapa não remove o ponto depois do leafletView.ProcessView(); tudo que gostaria de saber é se é possivel criar uma extensão de RemoveMarkers() para remover somente um item de uma lista de objetos.

segue abaixo o código funcionado:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>AngularPrune</title>


<link rel="stylesheet" type="text/css" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css">
<script type='text/javascript' src="http://code.angularjs.org/1.2.2/angular.js"></script>
<script type='text/javascript' src="http://tombatossals.github.io/angular-leaflet-directive/dist/angular-leaflet-directive.min.js"></script>
<script type='text/javascript' src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>


<script src="lib/dist/PruneCluster.js"></script>
<link rel="stylesheet" href="lib/dist/LeafletStyleSheet.css"/>

  <style type='text/css'>
  </style>

</head>
<body ng-app="AngularPrune">
  <body ng-controller="AngularPruneController">
    <leaflet center="center" markers="markers" layers="layers" width='800' height='400'></leaflet>
    <br>

    <button ng-click="removeMarkers()">Remove uidb Marker</button>

</body>


<script type='text/javascript'>

var app = angular.module('AngularPrune', ['leaflet-directive']);

app.controller('AngularPruneController', ['$scope', 'leafletData','leafletEvents', function ($scope, leafletData,leafletEvents) {

// 1 Make PruneCluster View
var leafletView = new PruneClusterForLeaflet(60);

    angular.extend($scope, {
        center: {
            lat:-22.911948,
                lng:-43.230162,
            zoom: 15
        },
        layers: {
            baselayers: {
                osm: {
                    name: 'OpenStreetMap',
                    url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    type: 'xyz'
                }
            },
            overlays: {
                markersOverlay: {
                    name: 'Markers',
                    type: 'group',
                    visible: true
                }
            },
             events: {
              map: {
              enable: ['context'],
              logic: 'emit'
            }
          }
        },

        markers: {
            "testMarker": {
                layer: 'markersOverlay',
                lat:-22.911948,
                lng:-43.232162,
                focus: false,
                message: 'My Marker on Leaflet',
                compileMessage: true
            }
        }


    });

           // Make Variable List of Object
           var markers = {};


          // Add Prune on map Layer 
          leafletData.getMap().then(function(map) {           


          function addPoint(uid, latitude,longitude) {     
          var marker = new PruneCluster.Marker(latitude,longitude);

         // Make Object List
          markers[uid] = marker;

          console.log(markers);
          leafletView.RegisterMarker(marker);
          leafletView.ProcessView();
          }

          addPoint('uida',-22.911948,-43.230162);
          addPoint('uidb',-22.911948,-43.230162);
          addPoint('uidc',-22.911948,-43.230162);

          console.log(markers['uida']);
          map.addLayer(leafletView);

         });

         var pos=0;

         // Test Cluster and UnCluster RealTime
            window.setInterval(function () {
                if(pos<100){
                markers['uida'].position.lng += 0.0001;
                }else{
                markers['uida'].position.lng -= 0.0001;
                if(pos>=200){
                pos=0;
                }
                }
                leafletView.ProcessView();
                pos++;
            },100);



          $scope.removeMarkers = function() {

             console.log(markers);
             delete markers['uidb'];    
             console.log(markers);
             leafletView.ProcessView();
          }


}]);

</script>
</body>
</html>
```

**Comment by JatGitHub** [comment]
Jeroeni

ivanssa <notifications@github.com>schreef:

>Olá  yellowiscool eu estou tendo alguns avanços no código, tenho apenas uma dúvida estou enviando um código base do PruneCluster funcionando com Angular, eu precisei utilizar uma lista de objetos ao invés de array para poder acessar o item através do código uid, a solução que me passou de remover os pontos através do markersBeingRemoved() funcionou, porém estou trabalhando com firebase e não posso criar uma lista, somente remover um ponto de cada vez e com a esta solução preciso fazer vários forEach e criar vários arrays markersBeingRemoved só pra remover um item o que ficou lento para trabalhar, assim eu consegui estudei e axei uma maneira de remover um item da lista de objetos através do  "delete markers['uidb']" mas o mapa não remove o ponto depois do leafletView.ProcessView(); tudo que gostaria de saber é se é possivel criar uma extensão de RemoveMarkers() para remover somente um item de uma lista de objetos.
>
>segue abaixo o código funcionado:
>
>```
><!DOCTYPE html>
><html>
><head>
>  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
>  <title>AngularPrune</title>
>
>
><link rel="stylesheet" type="text/css" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css">
><script type='text/javascript' src="http://code.angularjs.org/1.2.2/angular.js"></script>
><script type='text/javascript' src="http://tombatossals.github.io/angular-leaflet-directive/dist/angular-leaflet-directive.min.js"></script>
><script type='text/javascript' src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>
>
>
><script src="lib/dist/PruneCluster.js"></script>
><link rel="stylesheet" href="lib/dist/LeafletStyleSheet.css"/>
>
>  <style type='text/css'>
>  </style>
>
></head>
><body ng-app="AngularPrune">
>  <body ng-controller="AngularPruneController">
>    <leaflet center="center" markers="markers" layers="layers" width='800' height='400'></leaflet>
>    <br>
>
>    <button ng-click="removeMarkers()">Remove uidb Marker</button>
>
></body>
>
>
><script type='text/javascript'>
>
>var app = angular.module('AngularPrune', ['leaflet-directive']);
>
>app.controller('AngularPruneController', ['$scope', 'leafletData','leafletEvents', function ($scope, leafletData,leafletEvents) {

**Comment by yellowiscool** [comment]
Hei,

You should do the difference between an array and an object. If you use a string as key, you don't use the collection as an array but as an object (or a map/hashmap).

PruneCluster uses an array and doesn't use the delete keyword. You could try to optimize RemoveMarkers when you remove only one marker, but it will be in O(n).
You could try with [Array.prototype.splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

**Comment by ivanssa** [comment]
hello yellowiscool, I decided to keep the structure of PruneCluster as linear vector rather than objects and remove the following items through data.id with the solution that u showed me, but I decided to rewrite the function of RemoveMarkers () so that it can receive an item and make only one is instead of having to create a list to remove only one item, so it had to create a type as a parameter to define which type of removal will be executed and everything went well :-) thanks again for your help, check below as was the final function rewritten and removal methods:

```
PruneCluster.prototype.RemoveMarkers = function (markers, type) {
		
			switch(type) {
			case 'item':
				alert('item');
				for (var i = 0; i < this._markers.length; i++) {
				if (this._markers[i].data.uid === markers){
				this._markers.splice(i+1);
				}
				}	
				
				break;
			case 'list':
				alert('list');
				var newMarkersList = [];	
				
				for (var i = 0, l = markers.length; i < l; ++i) {
                markers[i]._removeFlag = true;
				}
				
				var newMarkersList = [];
				
				for (i = 0, l = this._markers.length; i < l; ++i) {
                if (!this._markers[i]._removeFlag) {
                    newMarkersList.push(this._markers[i]);
                }
				}
				
				this._markers = newMarkersList;
				
				break;
			case 'all':
				alert('all');
				this._markers = [];
                return;
				
				break;
			default:
				
			} 

        };
```

Metodos para remoção:

REMOVE LIST
```
 var markersBeingRemoved = [];
				leafletView.GetMarkers().forEach((marker) => {
					if (marker.data.uid === 'my uid') markersBeingRemoved.push(marker);
				});
			 
leafletView.RemoveMarkers(markersBeingRemoved,'list');
```

REMOVE ITEM BY DATA ID
```
leafletView.RemoveMarkers('my uid','list');
```

REMOVE ALL
```
leafletView.RemoveMarkers(markers,'list');
```

See if done right, and if we can add this functionality to a next update PruneCluster.
