### ISSUE TITLE
How to disable the zoom and Cluster 

### ISSUE THREAD

**Issue by ivanssa** [SINTEF-9012/PruneCluster#96]
Hello would like to know how to disable the zoom and cluster when you click a cluster group, I would like to open a popup instead of zoom and decluster and only do decluster if I increase the map zoom through the zoom buttons or zoom gesture.

**Comment by yellowiscool** [comment]
Hi,

I would go for the [BuildLeafletCluster method we discussed before](https://github.com/SINTEF-9012/PruneCluster/issues/92), and play with Leaflet's API directly.

**Comment by ivanssa** [comment]
Solved the problem of multiple clicks but still have to click once to activate the focus of prunecluster and then click again to open the popup, would focus on how to start the layer of prunecluster?

**Comment by ivanssa** [comment]
Hello apparently managed to solve was a problem with the marker.bindPopup function (popup); so I moved to openOn (map) and it worked thank you for your attention:
 
old code: (bug)
```
              var popup = L.popup()
             .setContent ('my content');				
             marker.bindPopup(popup);
```
new code (work)
```
              popup2 L.popup = var ()
             .setLatLng (marker.getLatLng ())
             .setContent ('my content')
             .openOn (map);

```

**Comment by yellowiscool** [comment]
Great to see that you found a solution :)

**Comment by ivanssa** [comment]
Tanks :+1:

**Comment by ivanssa** [comment]
Staff just to reinforce was still having problems with popup opening, the error occurred because he was using ionic and when altered the page to return to the map would not open more popup after much searching found the solution here http: // www. travisneufeld.com/fixing-click-events-with-ionic-and-leafletgoogle-maps/, which is very simple is a tip for those who want to work with Prune Leaflet + + + Ionic Popup ...

just add data-tap-disabled = "true" to the ion-view everything starts to work perfectly ...
